### ISSUE TITLE
Louvain 'community' failed

### ISSUE THREAD

**Issue by aleksberic** [sestaton/Transposome#41] opened 2017-12-07 14:57 UTC
Hi,

I am getting the following error:

Louvain 'community' failed. Caught error: "/usr/local/bin/louvain_community sample.fastq.interleave.500k.fa_PID90_COV55/sample_R1_allvall_blast_louvain.bin -l -1 -w sample.fastq.interleave.500k.fa_PID90_COV55/sample_R1_allvall_blast_louvain.tree.weights -v >sample.fastq.interleave.500k.fa_PID90_COV55/sample_R1_allvall_blast_louvain.tree 2>sample.fastq.interleave.500k.fa_PID90_COV55/sample_R1_allvall_blast_louvain.tree.log" unexpectedly returned exit value 139 at /usr/local/share/perl5/Transposome/Cluster.pm line 137.

I have many samples for which I've done the analysis, and most of them ran fine, but a couple fail with the mentioned error.
I'd appreciate help if anyone knows what might be going wrong.

Thanks

**Comment by sestaton** [comment] 2017-12-07 17:57
Hi,

First, please indicate the Transposome version you are using (`transposome --version`). The next thing to test is whether this is due to a memory issue. If you run the analysis and watch the memory does it approach 100%? Related to that, does this issue happen with fewer reads?

One way to quickly test a range of genome coverage values is to use the [full_analysis_with_varying_coverage.pl](https://github.com/sestaton/transposome-scripts/blob/master/full_analysis_with_varying_coverage.pl) script. That requires you to know the genome size, but if that's available (an estimate is fine), you can figure out if higher values of genome coverage are causing memory issues.

It could also be that the sample of reads contains many simple repeats. I recommend taking multiple random samples at the same coverage value and testing each. That also gives you an estimate of variance for determining repetitiveness.

**Comment by aleksberic** [comment] 2017-12-12 19:16
Hi,

Thank you for your reply. Sorry to respond just now, I was re-running one of the samples, changing some of the parameters to see if it'll work.
The version I'm using is 0.12.1.
In my most recent run I changed "in_memory:" clustering option in configuration file to 0 and that seems to solve the problem. 
I will try running the other problematic samples with the same configuration and see if they run okay.

Thanks

**Comment by sestaton** [comment] 2017-12-19 16:44
Thanks for the response. It sounds like it could simply be a memory issue, though it would be nice to know if the problem is solved or if there is some other way I could help.

**Comment by sestaton** [comment] 2018-10-10 15:22
Closing this as it seems to be solved. Please update if you have any further issues.

**Closed by sestaton** 2018-10-10 15:22 UTC
