### ISSUE TITLE
parse_blast format error

### ISSUE THREAD

**Issue by etwatson** [sestaton/Transposome#26] opened 2015-05-22 03:45 UTC
I've been having issues with  Transposome::PairFinder::parse_blast taking an hour with 280,000 sequences, but > 30 hours with 300,000 sequences (I cancelled it), so I moved to a different machine with a better CPU. With 300K sequences thats ~ 0.12x coverage, and I wonder if even that is enough. 

I'm not sure how to troubleshoot this, but I am getting the following error from  the _validate_format subroutine in Transposome::PairFinder::parse_blast:

```
INFO - ======== Transposome version: 0.09.6 (started at: 21-05-2015 20:22:14) ========
INFO - Configuration - Log file for monitoring progress and errors: ArthroTE_150k_t_log.txt
INFO - Configuration - Sequence file:                               /home/eric/Dropbox/tigriopus_genome/transposome/SD-500_150k.interleaved.fastq
INFO - Configuration - Sequence format:                             fastq
INFO - Configuration - Sequence number for each BLAST process:      10000
INFO - Configuration - Number of CPUs per thread:                   1
INFO - Configuration - Number of threads:                           7
INFO - Configuration - Output directory:                            SD_150k_results_out
INFO - Configuration - In-memory analysis:                          0
INFO - Configuration - Percent identity for matches:                85
INFO - Configuration - Fraction coverage for pairwise matches:      0.55
INFO - Configuration - Merge threshold for clusters:                0.001
INFO - Configuration - Minimum cluster size for annotation:         100
INFO - Configuration - BLAST e-value threshold for annotation:      10
INFO - Configuration - Repeat database for annotation:              /home/eric/Dropbox/tigriopus_genome/transposome/ArthroTE.fa
INFO - Configuration - Log file for clustering/merging results:     ArthroTE_150k_t_cluster_report.txt

INFO - Transposome::Run::Blast::run_allvall_blast started at:   21-05-2015 20:01:45.
INFO - Transposome::Run::Blast::run_allvall_blast finished running mgblast on 300000 sequences in 4.30 minutes.
INFO - Transposome::Run::Blast::run_allvall_blast completed at: 21-05-2015 20:06:03. Final output file is:
SD-500_150k.interleaved_allvall_blast.bln.
INFO - Transposome::PairFinder::parse_blast started at:   21-05-2015 20:06:03.
ERROR - 'HWI-ST279:217:D0F1BACXX:2:2205:17933:122967/1	101	81	1	HWI-ST279:217:D0F1BACXX:2:130HWI-ST279:217:D0F1BACXX:2:2105:16462:100877/1	101	101	25	HWI-ST279:217:D0F1BACXX:2:1306:14453:170461/1	101	23	101	93.75	267	4e-26	-' is not the correct format in file: Transposome::PairFinder=HASH(0x35cb938)->file. Exiting.
```

**Comment by etwatson** [comment] 2015-05-22 04:00
Here is the offending line, flanked by two good lines. I'm going to remove it and proceed.

```
HWI-ST279:217:D0F1BACXX:2:2105:16462:100877/2	101	101	25	HWI-ST279:217:D0F1BACXX:2:1306:14453:170461/2	101	23	101	93.75	267	4e-26	-
HWI-ST279:217:D0F1BACXX:2:2205:17933:122967/1	101	81	1	HWI-ST279:217:D0F1BACXX:2:130HWI-ST279:217:D0F1BACXX:2:2105:16462:100877/1	101	101	25	HWI-ST279:217:D0F1BACXX:2:1306:14453:170461/1	101	23	101	93.75	267	4e-26	-
HWI-ST279:217:D0F1BACXX:2:2105:16462:100877/2	101	101	25	HWI-ST279:217:D0F1BACXX:2:1306:14453:170461/1	101	23	101	93.75	267	4e-26	-
```

**Comment by sestaton** [comment] 2015-05-22 04:35
Yes, 0.1X coverage is sufficient (there are examples from maize in the supplement of the Transposome paper). For the error, it was handled correctly but it is not obvious why it occurred because the sequence IDs are correct. Is there a way you could share the sequence file? I'd like to test it out myself.

**Comment by sestaton** [comment] 2015-06-02 12:16
This issue appears to be caused by running the analysis in the Dropbox folder, so I will close this.

**Closed by sestaton** 2015-06-02 12:16 UTC
